eric = Friend.create(name: "Eric")

#angry
angry_resource1 = Resource.create(feeling: "angry/frustrated", resource: "Exercise! Jumping Jacks - 30 seconds. Plank - 30 seconds. Bicycle Crunches - 30 seconds.")
angry_resource2 = Resource.create(feeling: "angry/frustrated", resource: "Breathe. The moment you become angry, close your eyes and take a few deep breaths and observe the change in your state of mind. Breath releases stress and instantly calms the mind and body.")
angry_resource3 = Resource.create(feeling: "angry/frustrated", resource: "It’s okay to feel angry.")
angry_resource4 = Resource.create(feeling: "angry/frustrated", resource: "The Office episodes for when you want to laugh: S2: E1 'The Dundies'. S5: E26 'Casual Friday'. S7: E17 'Threat Level Midnight'")
angry_resource5 = Resource.create(feeling: "angry/frustrated", resource: "Have you tried venting? Cry. Punch (a pillow). Write. Exercise. Talk. Create art.")
angry_resource6 = Resource.create(feeling: "angry/frustrated", resource: "NYC Well is your connection to free, confidential mental health support. Text WELL to 65173. Call 1-888-NYC-WELL. 24/7 support.")

#bored/unmotivated/lazy
bored_resource1 = Resource.create(feeling: "bored/unmotivated/lazy", resource: "Rub a small amount of peppermint oil on your temples to wake up!")
bored_resource2 = Resource.create(feeling: "bored/unmotivated/lazy", resource: "Try these energizing workouts. Jumping Jacks - 30 seconds. Plank - 30 seconds. Bicycle Crunches - 30 seconds.")
bored_resource3 = Resource.create(feeling: "bored/unmotivated/lazy", resource: "Wanna feel like a boss? I’ve got the book for you. “You Are a Badass: How to Stop Doubting Your Greatness and Start Living an Awesome Life” by Jen Sincero.")
bored_resource4 = Resource.create(feeling: "bored/unmotivated/lazy", resource: "Did you know the 3 most common languages in the world are Mandarin, Chinese, Spanish, and English? Learn a new language with Duolingo!")
bored_resource5 = Resource.create(feeling: "bored/unmotivated/lazy", resource: "Would you rather have unlimited sushi for life or unlimited tacos for life?")
bored_resource6 = Resource.create(feeling: "bored/unmotivated/lazy", resource: "NYC Well is your connection to free, confidential mental health support. Text WELL to 65173. Call 1-888-NYC-WELL. 24/7 support.")

#hungry/thirsty
hungry1 = Resource.create(feeling: "hungry/thirsty", resource: "Next time you go out for a drink, impress your friends and put your bartender to the test by ordering the delicious apple infused Whirling Tiger.")
hungry2 = Resource.create(feeling: "hungry/thirsty", resource: "Mmm what about a Shepherd’s Pie? Two key, magical ingredients: potato and beef. Look up the dish for the full recipe!")
hungry3 = Resource.create(feeling: "hungry/thirsty", resource: "Out of ideas? Go check your fridge, make an inventory of what you’ve got and then look up online recipe generators to see what you can make out of the ingredients that you have.")
hungry4 = Resource.create(feeling: "hungry/thirsty", resource: "Go eat something you sillybilly! Maybe some string cheese? Or perhaps you’re more of a fresh fruit person? Or, lasagna? Perhaps you’d prefer a stew of some kind. Um... do you like kebabs?")
hungry5 = Resource.create(feeling: "hungry/thirsty", resource: "Drink WATER. NYC tap water is delicious. If you’re not in NYC maybe check first before drinking the tap water? It’s probably fine though. Well, find some water wherever you can. Even if you think you’re super hungry a glass of water is never a bad idea.")

#anxious/nervous/confused
anxious1 = Resource.create(feeling: "anxious/nervous/confused", resource: "Try this: sit in a chair with both feet on the ground. Feel the ground supporting your feet. Close your eyes and inhale deeply through your nose so the air goes all the way into your belly. As you inhale count 1...2...3...4...5...6...7. Hold the breath for another seven counts. Then exhale through your mouth for another seven counts. Repeat ten times.")
anxious2 = Resource.create(feeling: "anxious/nervous/confused", resource: "If you can, convince yourself that an anxiety is a normal response to a perceived threat. It isn’t anything to be overly concerned about health-wise. Also, it won’t keep going on indefinitely. You won’t always feel this way.")
anxious3 = Resource.create(feeling: "anxious/nervous/confused", resource: "Here are some images you might focus on: three fluffy clouds traveling across the sky at sunset. A sleeping puppy cuddled up next to a sleeping lamb cuddled up next to a sleeping baby giraffe. Dipping your toe into a lake surrounded by beautiful old trees. Finding out that the water is the absolute perfect temperature for you. Swimming in the clean, cool water and emerging, refreshed.")
anxious4 = Resource.create(feeling: "anxious/nervous/confused", resource: "Don’t worry, you’re going to be okay. You are good, and healthy, and smart. Also this app is secretly magic and will cure all your anxiety and other miscellaneous problems you might have.")
anxious5 = Resource.create(feeling: "anxious/nervous/confused", resource: "Try to bring to mind sounds that relax you. Maybe the sound of a waterfall. A beautiful voice singing a lullaby just for you. Someone saying they love you and meaning it. A light rain on the roof when you’re inside a happy home, warm, safe, and comfortable.")

#lonely/sad/hopeless
lonely1 = Resource.create(feeling: "lonely/sad/hopeless", resource: "Rainer Maria Rilke wrote this in 1904: ‘The only sadnesses that are dangerous and unhealthy are the ones that we carry around in public in order to drown them out with the noise; like diseases that are treated superficially and foolishly, they just withdraw and after a short interval break out again all the more terribly; and gather inside us and are life, are life that is unlived, rejected, lost, life that we can die of. If only it were possible for us to see farther than our knowledge reaches, and even a little beyond the outworks of our presentiment, perhaps we would bear our sadnesses with greater trust than we have in our joys.’ From Letters to a Young Poet, #8")
lonely2 = Resource.create(feeling: "lonely/sad/hopeless", resource: "Imagine you are being snuggled by lots of fluffy baby goats, like a woman I watched on Youtube once.")
lonely3 = Resource.create(feeling: "lonely/sad/hopeless", resource: "Many people around the world feel the way way you are feeling. In the US, one in twelve adults in the US suffer from depression. People are medicating themselves left and right with drugs, both legal and illegal. Find comfort knowing that you are not alone. Life can be very difficult, even for the luckiest and seemingly happiest people.")
lonely4 = Resource.create(feeling: "lonely/sad/hopeless", resource: "Try to start observing the trends in your feelings. Do you feel sad just now, or every day? Do you feel sad more often at a particular time of day? Where in your body do you feel the sadness? Is it simply a physical feeling, or coupled with thoughts as well? Documenting your emotions can help you understand when and where they come from so you don’t get caught totally unaware.")
lonely5 = Resource.create(feeling: "lonely/sad/hopeless", resource: "Here, temporarily distract yourself with this friendly joke: ‘Everybody knows the saying: 'You should never go to the grocery store when you're hungry.' But there's another saying that I don't think they tell you enough which is this: 'You should never go to the pet store when you're lonely.' Not funny? Okay, here’s another: ‘What’s brown and sticky? A stick!’ Haha! Classic.")
